test3

diff --git a/.github/workflows/generate-builds.yml b/.github/workflows/generate-builds.yml
--- a/.github/workflows/generate-builds.yml
+++ b/.github/workflows/generate-builds.yml
@@ -54,68 +54,6 @@ jobs:
         name: soh.otr
         path: soh.otr
         retention-days: 1
-  build-macos:
-    needs: generate-soh-otr
-    runs-on: macos-14
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        submodules: true
-    - name: ccache
-      uses: hendrikmuhs/ccache-action@v1.2.13
-      with:
-        create-symlink: true
-        key: ${{ runner.os }}-14-ccache-${{ github.ref }}-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-14-ccache-${{ github.ref }}
-          ${{ runner.os }}-14-ccache-
-    - name: Install gtar wrapper
-      run: |
-        sudo mv /opt/homebrew/bin/gtar /opt/homebrew/bin/gtar.orig
-        sudo cp .github/workflows//gtar /opt/homebrew/bin/gtar
-        sudo chmod +x /opt/homebrew/bin/gtar
-    - name: Cache MacPorts
-      id: cache-macports
-      uses: actions/cache@v4
-      with:
-        path: /opt/local/
-        key: ${{ runner.os }}-14-macports-${{ hashFiles('.github/workflows/macports-deps.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-14-macports-
-    - name: Install MacPorts (if necessary)
-      run: |
-        if [ -d /opt/local/ ]; then
-          echo "MacPorts already installed"
-        else
-          wget https://github.com/macports/macports-base/releases/download/v2.9.3/MacPorts-2.9.3-14-Sonoma.pkg
-          sudo installer -pkg ./MacPorts-2.9.3-14-Sonoma.pkg -target /
-        fi
-        echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH
-    - name: Install dependencies
-      run: |
-        brew uninstall --ignore-dependencies libpng
-        sudo port install $(cat .github/workflows/macports-deps.txt)
-        brew install ninja
-    - name: Download soh.otr
-      uses: actions/download-artifact@v4
-      with:
-        name: soh.otr
-    - name: Build SoH
-      run: |
-        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DBUILD_REMOTE_CONTROL=1
-        cmake --build build-cmake --config Release --parallel 10
-        mv soh.otr build-cmake/soh
-        (cd build-cmake && cpack)
-
-        mv _packages/*.dmg SoH.dmg
-        mv README.md readme.txt
-    - name: Upload build
-      uses: actions/upload-artifact@v4
-      with:
-        name: soh-mac
-        path: |
-          SoH.dmg
-          readme.txt
   build-linux:
     needs: generate-soh-otr
     strategy:
@@ -128,7 +66,7 @@ jobs:
         - os: ubuntu-22.04
           gcc: 12
           archive-suffix: performance
-    runs-on: ubuntu-latest # Temporary for testing; revert to original after confirming
+    runs-on: ${{ (matrix.os == 'ubuntu-20.04' && ((vars.LINUX_COMPATIBILITY_RUNNER && fromJSON(vars.LINUX_COMPATIBILITY_RUNNER)) || matrix.os)) || (matrix.os == 'ubuntu-22.04' && ((vars.LINUX_PERFORMANCE_RUNNER && fromJSON(vars.LINUX_PERFORMANCE_RUNNER)) || matrix.os)) }}
     steps:
     - uses: actions/checkout@v4
       with:
@@ -143,7 +81,13 @@ jobs:
       if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
       run: |
         sudo apt-get update
-        sudo apt-get install -y build-essential libbz2-dev python3-dev zlib1g-dev libboost-all-dev $(cat .github/workflows/apt-deps.txt)
+        sudo apt-get install -y build-essential libbz2-dev python3-dev zlib1g-dev libboost-all-dev gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }} $(cat .github/workflows/apt-deps.txt)
+    - name: Debug compilers
+      run: |
+        gcc --version
+        g++ --version
+        gcc-${{ matrix.gcc }} --version
+        g++-${{ matrix.gcc }} --version
     - name: Check Boost version
       if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
       run: |
@@ -155,7 +99,7 @@ jobs:
     - name: Install latest SDL
       if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
       run: |
-        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
+        export PATH="/usr/lib/ccache:$PATH"
         wget https://www.libsdl.org/release/SDL2-2.26.1.tar.gz
         tar -xzf SDL2-2.26.1.tar.gz
         cd SDL2-2.26.1
@@ -166,7 +110,7 @@ jobs:
     - name: Install latest SDL_net
       if: ${{ (matrix.os == 'ubuntu-20.04' && !vars.LINUX_COMPATIBILITY_RUNNER) || (matrix.os == 'ubuntu-22.04' && !vars.LINUX_PERFORMANCE_RUNNER) }}
       run: |
-        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
+        export PATH="/usr/lib/ccache:$PATH"
         wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.2.0.tar.gz
         tar -xzf SDL2_net-2.2.0.tar.gz
         cd SDL2_net-2.2.0
@@ -180,11 +124,10 @@ jobs:
         name: soh.otr
     - name: Build SoH
       run: |
-        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
-        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_REMOTE_CONTROL=1
-        cmake --build build-cmake --config Release -j3
+        export PATH="/usr/lib/ccache:$PATH"
+        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_REMOTE_CONTROL=1 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
+        cmake --build build-cmake --config Release -j3 --verbose
         (cd build-cmake && cpack -G External)
-
         mv README.md readme.txt
         mv build-cmake/*.appimage soh.appimage
       env:
@@ -206,6 +149,12 @@ jobs:
       run: |
         choco install ninja
         Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
+    - name: Debug environment
+      run: |
+        choco list --local-only
+        ninja --version
+        cmake --version
+        dir ${{github.workspace}}\vcpkg
     - uses: actions/checkout@v4
       with:
         submodules: true
@@ -216,9 +165,10 @@ jobs:
     - name: vcpkg
       uses: johnwason/vcpkg-action@v5
       with:
-        pkgs: zlib bzip2 libpng sdl2 sdl2-net glew glfw3
+        pkgs: zlib bzip2 libpng sdl2 sdl2-net glew glfw3 boost
         token: ${{ github.token }}
-        triplet: 'x64-windows-static'
+        triplet: x64-windows-static
+        additional-args: --debug
     - name: Configure Developer Command Prompt
       uses: ilammy/msvc-dev-cmd@v1
     - name: Build SoH
@@ -226,18 +176,19 @@ jobs:
         VCPKG_ROOT: ${{github.workspace}}/vcpkg
       run: |
         set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
-        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_REMOTE_CONTROL=1
-        cmake --build build-windows --config Release --parallel 10
-
+        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_REMOTE_CONTROL=1 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
+        if (-Not (Test-Path build-windows/build.ninja)) { Write-Error "build.ninja not found"; exit 1 }
+        cmake --build build-windows --config Release --parallel 10 --verbose
+        if (-Not (Test-Path build-windows/soh.exe)) { Write-Error "soh.exe not found"; exit 1 }
         mkdir soh-windows
-        mv ./x64/Release/soh.exe ./soh-windows/soh.exe
+        mv build-windows/soh.exe soh-windows/soh.exe
         mkdir soh-windows/debug
         mkdir soh-windows/mods
         New-Item soh-windows/mods/custom_otr_files_go_here.txt -type file
-        mv ./x64/Release/soh.pdb ./soh-windows/debug/soh.pdb
-        mv ./README.md ./soh-windows/readme.txt
-        mv ./build-windows/gamecontrollerdb.txt ./soh-windows/gamecontrollerdb.txt
-        mv ./x64/Release/assets ./soh-windows
+        mv build-windows/soh.pdb soh-windows/debug/soh.pdb
+        mv README.md soh-windows/readme.txt
+        mv build-windows/gamecontrollerdb.txt soh-windows/gamecontrollerdb.txt
+        mv build-windows/assets soh-windows
     - name: Download soh.otr
       uses: actions/download-artifact@v4
       with:
